# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    admin.articles:
        class: wp\AssociationBundle\Admin\ArticlesAdmin
        arguments: [~, wp\AssociationBundle\Entity\Articles, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Articles }
    admin.auteur:
        class: wp\AssociationBundle\Admin\AuteurAdmin
        arguments: [~, wp\AssociationBundle\Entity\Auteur, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Auteur }
